#!/usr/bin/env python3
"""Fail closed on avoidable publication defects without making a license decision."""
from __future__ import annotations
import argparse, json, re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
PLACEHOLDERS = ("FINALITY-OWNER", "FINALITY-REPOSITORY")
TEXT_EXT = {'.md','.json','.jsonl','.yaml','.yml','.py','.ts','.mts','.js','.mjs','.sh','.tla','.cfg','.cff','.txt'}
STANDARD_RUNNERS = {'ubuntu-latest','macos-latest','windows-latest'}

def fail(msgs):
    print('PREPUBLICATION: FAIL')
    for m in msgs: print(m)
    return 1

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--publish', action='store_true', help='also require explicit license/publication authorization')
    args=ap.parse_args()
    findings=[]
    # Generated bytecode must never ship.
    for p in ROOT.rglob('*'):
        if p.is_dir() and p.name == '__pycache__': findings.append(f'GENERATED_BYTECODE_DIR:{p.relative_to(ROOT)}')
        if p.is_file() and p.suffix == '.pyc': findings.append(f'GENERATED_BYTECODE_FILE:{p.relative_to(ROOT)}')
    # No unresolved repository placeholders in publishable text.
    for p in ROOT.rglob('*'):
        if not p.is_file() or '.git' in p.parts or p.suffix.lower() not in TEXT_EXT or p.resolve() == Path(__file__).resolve(): continue
        try: txt=p.read_text(encoding='utf-8')
        except UnicodeDecodeError: continue
        for token in PLACEHOLDERS:
            if token in txt: findings.append(f'PLACEHOLDER:{token}:{p.relative_to(ROOT)}')
    # Do not claim a license in Zenodo metadata before a real LICENSE exists.
    zp=ROOT/'.zenodo.json'
    if zp.exists():
        z=json.loads(zp.read_text(encoding='utf-8'))
        if not (ROOT/'LICENSE').exists() and z.get('license'):
            findings.append('ZENODO_LICENSE_ASSERTED_WITHOUT_LICENSE_FILE')
    # CFF must not assert repository/license that does not exist yet.
    cff=(ROOT/'CITATION.cff').read_text(encoding='utf-8')
    if 'FINALITY-OWNER' in cff or 'FINALITY-REPOSITORY' in cff: findings.append('CITATION_REPOSITORY_PLACEHOLDER')
    # Public workflows must only select free standard runner labels.
    for wf in (ROOT/'.github/workflows').glob('*.yml'):
        txt=wf.read_text(encoding='utf-8')
        for m in re.finditer(r'runs-on:\s*([^\n]+)', txt):
            val=m.group(1).strip().strip('"\'')
            if '${{' in val: continue
            if val not in STANDARD_RUNNERS: findings.append(f'NONSTANDARD_RUNNER:{wf.name}:{val}')
    if args.publish:
        if not (ROOT/'LICENSE').exists(): findings.append('LICENSE_SELECTION_REQUIRED')
        auth=(ROOT/'PUBLICATION_AUTHORIZATION.md')
        if not auth.exists() or 'PUBLIC RELEASE AUTHORIZED: YES' not in auth.read_text(encoding='utf-8'):
            findings.append('EXPLICIT_PUBLICATION_AUTHORIZATION_REQUIRED')
    if findings: return fail(findings)
    print('PREPUBLICATION: READY' if not args.publish else 'PREPUBLICATION: PUBLISH AUTHORIZED')
    return 0
if __name__ == '__main__': raise SystemExit(main())
