name: ClusterFuzzLite coverage

on:
  schedule:
    - cron: "41 2 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Build coverage fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05
        with:
          language: python
          sanitizer: coverage
      - name: Generate coverage
        uses: google/clusterfuzzlite/actions/run_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: coverage
          sanitizer: coverage
          language: python
