name: ClusterFuzzLite batch fuzzing

on:
  schedule:
    - cron: "11 2 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - name: Build fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05
        with:
          language: python
      - name: Run scheduled batch
        uses: google/clusterfuzzlite/actions/run_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 1800
          mode: batch
          sanitizer: address
          language: python
